"""The top-down replay, which is derived and never a recording.

The replay exists so a reader can see WHY a configuration failed rather than
read that it did, which makes it evidence, and evidence has to be exactly as
trustworthy as the numbers beside it.

IT IS DERIVED. Every frame is built from the same world state the AEB acted on:
oriented boxes, the ego's footprint, the time to collision and the state
timeline. There is no camera image and no lidar point anywhere in this project,
and this is the module most likely to acquire one by accident, so a test asserts
that no field here names a sensor.

IT SHOWS WHAT THE CONTROLLER SAW. A dropped track is drawn as dropped rather
than omitted; omitting it would make a missed intervention look inexplicable,
which is the opposite of what the replay is for.

THE ANIMATION IS GENERATED BY PYTHON. This project ships no first-party
JavaScript, because a hand-written player would be untested code sitting between
a result and the person reading it. The plotly figure is written as
self-contained HTML with a FIXED div id, so two builds of the same timeline
produce identical bytes and a report can be checked by rebuilding it.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional

import plotly.graph_objects as go
import plotly.io as pio

from aebrisk.aeb.state_machine import AEBState
from aebrisk.aeb.threat import oriented_box_polygon
from aebrisk.observation.models import TrackState

#: How an object the controller could see is drawn, and how one it could not is.
#: Two names that resolved to one value would make the distinction invisible.
STYLE_OBSERVED = "observed"
STYLE_UNOBSERVED = "unobserved"

#: Fixed rather than generated, so the written HTML is byte-identical between
#: builds. Plotly's default is a random UUID.
REPLAY_DIV_ID = "aeb-replay"
REPLAY_NOTICE = (
    "Derived visualization; no sensor pixels or map data. "
    "nuPlan-derived geometry is shared under CC BY-NC-SA 4.0 and Motional terms. "
    "Plotly.js is MIT licensed."
)


@dataclass(frozen=True)
class ReplayFrame:
    """One simulation step, as the reader sees it."""

    time_s: float
    ego_center_xy_m: tuple[float, float]
    ego_yaw_rad: float
    ego_size_lw_m: tuple[float, float]
    ego_speed_mps: float
    tracks: tuple[TrackState, ...]
    aeb_state: AEBState
    ttc_s: Optional[float]

    def __post_init__(self) -> None:
        if not math.isfinite(self.time_s) or self.time_s < 0.0:
            raise ValueError("time_s must be finite and non-negative")


def _closed(polygon: Any) -> tuple[tuple[float, float], ...]:
    """Repeat the first vertex so the ring draws closed.

    An open ring draws as a three-sided box, which reads as a bug in the data
    rather than as a drawing detail.
    """

    points = [(float(x), float(y)) for x, y in polygon]
    return (*points, points[0])


def frame_polygons(frame: ReplayFrame) -> dict[str, tuple[tuple[float, float], ...]]:
    """The closed outline of the ego and of every track, by identity."""

    shapes = {
        "ego": _closed(
            oriented_box_polygon(frame.ego_center_xy_m, frame.ego_yaw_rad, frame.ego_size_lw_m)
        )
    }
    for track in frame.tracks:
        shapes[track.track_id] = _closed(
            oriented_box_polygon(track.center_xy_m, track.yaw_rad, track.size_lw_m)
        )
    return shapes


def frame_styles(frame: ReplayFrame) -> dict[str, str]:
    """Whether each track was observed at this step."""

    return {
        track.track_id: STYLE_OBSERVED if track.visible else STYLE_UNOBSERVED
        for track in frame.tracks
    }


def _frame_title(title: str, frame: ReplayFrame) -> str:
    time_to_collision = "none" if frame.ttc_s is None else f"{frame.ttc_s:.2f} s"
    return (
        f"{_wrap_title(title)}<br>t={frame.time_s:.1f} s — {frame.aeb_state.value} — "
        f"{frame.ego_speed_mps:.1f} m/s — ttc {time_to_collision}"
    )


def _wrap_title(title: str, width: int = 32) -> str:
    """Insert display-only line breaks without changing scenario identity."""

    return "<br>".join(title[index : index + width] for index in range(0, len(title), width))


def _traces(frame: ReplayFrame, identities: tuple[str, ...]) -> list[go.Scatter]:
    polygons = frame_polygons(frame)
    styles = frame_styles(frame)

    traces = [
        go.Scatter(
            x=[point[0] for point in polygons["ego"]],
            y=[point[1] for point in polygons["ego"]],
            mode="lines",
            fill="toself",
            name="ego",
        )
    ]
    for identity in identities:
        outline = polygons.get(identity, ())
        observed = styles.get(identity) == STYLE_OBSERVED
        traces.append(
            go.Scatter(
                x=[point[0] for point in outline],
                y=[point[1] for point in outline],
                mode="lines",
                # An unobserved track is drawn dashed and unfilled: present in
                # the world, absent from what the controller was given.
                fill="toself" if observed else "none",
                line={"dash": "solid" if observed else "dash"},
                name=identity,
            )
        )
    return traces


def _axis_range(frames: tuple[ReplayFrame, ...], coordinate: int) -> tuple[float, float]:
    values = [
        point[coordinate]
        for frame in frames
        for polygon in frame_polygons(frame).values()
        for point in polygon
    ]
    low, high = min(values), max(values)
    padding = max(2.0, (high - low) * 0.05)
    return low - padding, high + padding


def build_replay_figure(frames: tuple[ReplayFrame, ...], title: str) -> go.Figure:
    """Build the animated top-down figure for one scenario and configuration."""

    if not frames:
        raise ValueError("there are no frames to replay")
    if not title:
        raise ValueError("title must name the scenario and configuration shown")

    identities = tuple(sorted({track.track_id for frame in frames for track in frame.tracks}))
    label_stride = max(1, math.ceil((len(frames) - 1) / 6))
    slider_steps = [
        {
            "args": [[f"{frame.time_s:.1f}"], {"frame": {"duration": 0, "redraw": True}}],
            "label": (
                f"{frame.time_s:.1f} s"
                if index == 0 or index == len(frames) - 1 or index % label_stride == 0
                else ""
            ),
            "value": f"{frame.time_s:.1f} s",
            "method": "animate",
        }
        for index, frame in enumerate(frames)
    ]
    figure = go.Figure(
        data=_traces(frames[0], identities),
        layout=go.Layout(
            title={"text": _frame_title(title, frames[0]), "automargin": True},
            xaxis={
                "title": {"text": "scenario-local x (m)", "standoff": 16},
                "scaleanchor": "y",
                "range": _axis_range(frames, 0),
            },
            yaxis={"title": {"text": ""}, "range": _axis_range(frames, 1)},
            annotations=[
                {
                    "text": "scenario-local y (m)",
                    "textangle": 0,
                    "xref": "paper",
                    "yref": "paper",
                    "x": 0,
                    "y": 1.03,
                    "xanchor": "left",
                    "yanchor": "bottom",
                    "showarrow": False,
                }
            ],
            margin={"t": 110, "b": 150},
            showlegend=True,
            updatemenus=[
                {
                    "type": "buttons",
                    "x": 0,
                    "y": -0.3,
                    "xanchor": "left",
                    "yanchor": "top",
                    "buttons": [
                        {
                            "label": "Play",
                            "method": "animate",
                            "args": [None, {"frame": {"duration": 100, "redraw": True}}],
                        },
                        {
                            "label": "Pause",
                            "method": "animate",
                            "args": [[None], {"mode": "immediate", "frame": {"duration": 0}}],
                        },
                    ],
                }
            ],
            sliders=[
                {
                    "active": 0,
                    "ticklen": 0,
                    "x": 0.22,
                    "y": -0.12,
                    "len": 0.78,
                    "currentvalue": {"prefix": "time ", "xanchor": "left"},
                    "pad": {"t": 12, "b": 12},
                    "steps": slider_steps,
                }
            ],
        ),
        frames=[
            go.Frame(
                data=_traces(frame, identities),
                name=f"{frame.time_s:.1f}",
                layout=go.Layout(title={"text": _frame_title(title, frame)}),
            )
            for frame in frames
        ],
    )
    return figure


def write_replay_html(
    frames: tuple[ReplayFrame, ...],
    title: str,
    path: Path,
) -> None:
    """Write the replay as one self-contained HTML file.

    Self-contained so the site opens from a file with no network and no build
    step, and byte-identical between builds so a report can be checked by
    rebuilding it.
    """

    html = pio.to_html(
        build_replay_figure(frames, title),
        include_plotlyjs=True,
        full_html=True,
        div_id=REPLAY_DIV_ID,
        auto_play=False,
    )
    notice = f'<footer role="contentinfo"><p>{REPLAY_NOTICE}</p></footer>'
    html = html.replace("</body>", f"{notice}\n</body>")
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(html)
