"""Contracts for the top-down replay, which is derived and never a recording.

The replay exists so that a reader can see WHY a configuration failed, rather
than reading that it did. That makes it evidence, and evidence has to be exactly
as trustworthy as the numbers beside it.

IT IS DERIVED, NOT RECORDED. Every frame is built from the same world state the
AEB acted on: oriented boxes, the route, the time to collision and the state
timeline. There is no camera image and no lidar point anywhere in this project,
and this module is the one most likely to acquire one by accident, so a test
asserts that nothing it produces carries a sensor payload.

IT SHOWS WHAT THE CONTROLLER SAW, NOT WHAT WAS THERE. A dropped track is drawn
as dropped. A replay that quietly showed the oracle world would make every
missed intervention look inexplicable, which is the opposite of its purpose.

THE ANIMATION IS GENERATED BY PYTHON. This project ships no first-party
JavaScript: a hand-written player would be untested code sitting between a
result and the person reading it.
"""

from __future__ import annotations

from types import ModuleType
from typing import Any

import pytest


def load_replay_module() -> ModuleType:
    """Import inside the test so a missing module is a purposeful RED failure."""

    try:
        from aebrisk.report import replay
    except ImportError:
        pytest.fail("aebrisk.report.replay is missing", pytrace=False)
    return replay


def track(track_id: str, x: float, *, visible: bool = True) -> Any:
    from aebrisk.observation.models import TrackState

    return TrackState(
        track_id=track_id,
        category="vehicle",
        center_xy_m=(x, 0.0),
        yaw_rad=0.0,
        size_lw_m=(4.0, 2.0),
        velocity_xy_mps=(0.0, 0.0),
        visible=visible,
        source_timestamp_us=1_600_000_000_000_000,
        covariance_xy=(0.0, 0.0, 0.0, 0.0),
    )


def frame(index: int, *, state: str = "monitor", tracks: tuple = ()) -> Any:
    from aebrisk.aeb.state_machine import AEBState
    from aebrisk.report.replay import ReplayFrame

    return ReplayFrame(
        time_s=index * 0.1,
        ego_center_xy_m=(index * 1.0, 0.0),
        ego_yaw_rad=0.0,
        ego_size_lw_m=(4.0, 2.0),
        ego_speed_mps=10.0,
        tracks=tracks or (track("t-0001", 40.0),),
        aeb_state=AEBState(state),
        ttc_s=2.0,
    )


def timeline(count: int = 5) -> tuple:
    return tuple(frame(index) for index in range(count))


# --------------------------------------------------------------------------
# Frames
# --------------------------------------------------------------------------


def test_a_frame_carries_only_derived_world_state() -> None:
    """The field list is the guarantee, so it is asserted rather than described."""

    import dataclasses

    replay = load_replay_module()

    names = {field.name for field in dataclasses.fields(replay.ReplayFrame)}

    assert names == {
        "time_s",
        "ego_center_xy_m",
        "ego_yaw_rad",
        "ego_size_lw_m",
        "ego_speed_mps",
        "tracks",
        "aeb_state",
        "ttc_s",
    }


def test_no_frame_field_names_a_sensor() -> None:
    """This is the module most likely to acquire a camera by accident."""

    import dataclasses

    replay = load_replay_module()
    forbidden = ("image", "camera", "lidar", "pointcloud", "sensor", "blob")

    for field in dataclasses.fields(replay.ReplayFrame):
        assert not any(word in field.name.lower() for word in forbidden)


def test_a_frame_is_frozen() -> None:
    """It is the evidence for one step of a published result."""

    import dataclasses

    load_replay_module()
    one = frame(0)

    with pytest.raises(dataclasses.FrozenInstanceError):
        one.time_s = 9.0  # type: ignore[misc]


def test_a_frame_at_a_negative_time_is_refused() -> None:
    """Time before the scenario started means the timeline was built wrongly."""

    replay = load_replay_module()

    with pytest.raises(ValueError, match=r"^time_s\ must\ be\ finite\ and\ non\-negative"):
        replay.ReplayFrame(
            time_s=-0.1,
            ego_center_xy_m=(0.0, 0.0),
            ego_yaw_rad=0.0,
            ego_size_lw_m=(4.0, 2.0),
            ego_speed_mps=10.0,
            tracks=(),
            aeb_state=replay.AEBState.MONITOR,
            ttc_s=None,
        )


# --------------------------------------------------------------------------
# Polygons
# --------------------------------------------------------------------------


def test_the_ego_is_drawn_as_its_own_footprint() -> None:
    """A dot would hide exactly the geometry the threat assessment used."""

    replay = load_replay_module()

    polygon = replay.frame_polygons(frame(0))["ego"]

    assert len(polygon) == 5  # four corners, closed back to the first


def test_a_polygon_is_closed_for_drawing() -> None:
    """An open ring draws as a three-sided box, which reads as a bug in the data."""

    replay = load_replay_module()

    polygon = replay.frame_polygons(frame(0))["ego"]

    assert polygon[0] == polygon[-1]


def test_each_track_is_drawn_separately() -> None:
    """One shape per object, so a reader can follow an identity across frames."""

    replay = load_replay_module()
    one = frame(0, tracks=(track("t-0001", 40.0), track("t-0002", 20.0)))

    polygons = replay.frame_polygons(one)

    assert "t-0001" in polygons
    assert "t-0002" in polygons


def test_a_dropped_track_is_still_drawn() -> None:
    """It is drawn as dropped, not omitted.

    Omitting it would make a missed intervention look inexplicable, which is
    the opposite of what this replay is for.
    """

    replay = load_replay_module()
    one = frame(0, tracks=(track("t-0001", 40.0, visible=False),))

    assert "t-0001" in replay.frame_polygons(one)
    assert replay.frame_styles(one)["t-0001"] == replay.STYLE_UNOBSERVED


def test_an_observed_track_is_styled_differently() -> None:
    """The pair to the test above; one style for both would say nothing."""

    replay = load_replay_module()

    assert replay.frame_styles(frame(0))["t-0001"] == replay.STYLE_OBSERVED


def test_the_styles_are_distinct() -> None:
    """Two names that resolved to one value would make the distinction invisible."""

    replay = load_replay_module()

    assert replay.STYLE_OBSERVED != replay.STYLE_UNOBSERVED


# --------------------------------------------------------------------------
# The animation
# --------------------------------------------------------------------------


def test_the_animation_has_one_step_per_frame() -> None:
    """A reader scrubbing the timeline is scrubbing the simulation's own steps."""

    replay = load_replay_module()

    figure = replay.build_replay_figure(timeline(7), title="s-0001 / oracle_aeb")

    assert len(figure["frames"]) == 7


def test_animation_has_plotly_generated_play_pause_and_time_slider() -> None:
    replay = load_replay_module()

    figure = replay.build_replay_figure(timeline(3), title="t")

    labels = [button["label"] for button in figure["layout"]["updatemenus"][0]["buttons"]]
    assert labels == ["Play", "Pause"]
    assert [step["label"] for step in figure["layout"]["sliders"][0]["steps"]] == [
        "0.0 s",
        "0.1 s",
        "0.2 s",
    ]


def test_dense_timeline_keeps_every_frame_reachable_with_sparse_visible_ticks() -> None:
    replay = load_replay_module()

    figure = replay.build_replay_figure(timeline(31), title="t")
    steps = figure["layout"]["sliders"][0]["steps"]

    assert len(steps) == 31
    assert [step["args"][0][0] for step in steps] == [frame["name"] for frame in figure["frames"]]
    assert [step["value"] for step in steps] == [f"{index * 0.1:.1f} s" for index in range(31)]
    visible_labels = [step["label"] for step in steps if step["label"]]
    assert visible_labels[0] == "0.0 s"
    assert visible_labels[-1] == "3.0 s"
    assert len(visible_labels) <= 7
    assert figure["layout"]["sliders"][0]["ticklen"] == 0


def test_labels_and_controls_have_separate_readable_regions() -> None:
    replay = load_replay_module()

    figure = replay.build_replay_figure(timeline(), title="t")
    layout = figure["layout"]

    assert layout["yaxis"]["title"]["text"] in (None, "")
    y_explanation = next(
        annotation
        for annotation in layout["annotations"]
        if annotation["text"] == "scenario-local y (m)"
    )
    assert y_explanation["textangle"] == 0
    assert y_explanation["xref"] == "paper"
    assert y_explanation["yref"] == "paper"
    assert layout["updatemenus"][0]["y"] != layout["sliders"][0]["y"]
    assert layout["sliders"][0]["currentvalue"]["prefix"] == "time "
    assert layout["margin"]["b"] >= 120


def test_long_scenario_title_wraps_without_losing_its_identity() -> None:
    replay = load_replay_module()
    title = "scenario-with-an-intentionally-long-identity-token / observation_delayed_aeb"

    figure = replay.build_replay_figure(timeline(), title=title)
    rendered = figure["layout"]["title"]["text"]

    assert "<br>" in rendered
    assert title in rendered.replace("<br>", "")
    assert max(len(line) for line in rendered.split("<br>")[:-1]) <= 32


def test_actor_trace_indices_stay_stable_when_actors_enter_exit_or_reorder() -> None:
    replay = load_replay_module()
    frames = (
        frame(0, tracks=(track("actor-b", 20.0),)),
        frame(1, tracks=(track("actor-a", 10.0), track("actor-b", 21.0))),
        frame(2, tracks=(track("actor-b", 22.0), track("actor-a", 11.0))),
        frame(3, tracks=(track("actor-a", 12.0),)),
    )

    figure = replay.build_replay_figure(frames, title="t")

    expected_names = ["ego", "actor-a", "actor-b"]
    for animation_frame in figure["frames"]:
        assert [trace["name"] for trace in animation_frame["data"]] == expected_names
    assert figure["frames"][0]["data"][1]["x"] == ()
    assert figure["frames"][3]["data"][2]["x"] == ()


def test_serialized_frame_explicitly_clears_fill_when_actor_becomes_unobserved() -> None:
    import json

    replay = load_replay_module()
    frames = (
        frame(0, tracks=(track("actor-a", 20.0, visible=True),)),
        frame(1, tracks=(track("actor-a", 21.0, visible=False),)),
    )

    serialized = json.loads(replay.build_replay_figure(frames, title="t").to_json())

    assert serialized["frames"][0]["data"][1]["fill"] == "toself"
    assert serialized["frames"][1]["data"][1]["fill"] == "none"


def test_axes_cover_the_whole_timeline_instead_of_rescaling_each_frame() -> None:
    replay = load_replay_module()
    frames = (
        frame(0, tracks=(track("a", -20.0),)),
        frame(1, tracks=(track("a", 80.0),)),
    )

    figure = replay.build_replay_figure(frames, title="t")

    assert figure["layout"]["xaxis"]["range"][0] < -20.0
    assert figure["layout"]["xaxis"]["range"][1] > 80.0


def test_the_animation_is_titled_with_what_it_shows() -> None:
    """A replay nobody can attribute to a scenario and a cell is not evidence."""

    replay = load_replay_module()

    figure = replay.build_replay_figure(timeline(), title="s-0001 / oracle_aeb")

    assert "s-0001" in figure["layout"]["title"]["text"]


def test_the_animation_is_written_as_self_contained_html(tmp_path: Any) -> None:
    """The site must open from a file with no network and no build step."""

    replay = load_replay_module()
    path = tmp_path / "replay.html"

    replay.write_replay_html(timeline(), title="s-0001 / oracle_aeb", path=path)
    written = path.read_text(encoding="utf-8")

    assert written.lstrip().startswith("<")
    assert "plotly" in written.lower()
    assert "Derived visualization" in written
    assert "CC BY-NC-SA 4.0" in written
    assert "Plotly.js is MIT licensed" in written


def test_the_written_html_pins_its_line_ending(tmp_path: Any) -> None:
    """The same rule as every other artifact this portfolio writes.

    A file whose bytes depend on the platform that produced it cannot be
    compared between a developer's machine and CI.
    """

    replay = load_replay_module()
    path = tmp_path / "replay.html"

    replay.write_replay_html(timeline(), title="t", path=path)

    assert b"\r\n" not in path.read_bytes()


def test_the_same_timeline_produces_the_same_html(tmp_path: Any) -> None:
    """A report that differed between builds could not be checked by rebuilding it."""

    replay = load_replay_module()
    first, second = tmp_path / "a.html", tmp_path / "b.html"

    replay.write_replay_html(timeline(), title="t", path=first)
    replay.write_replay_html(timeline(), title="t", path=second)

    assert first.read_bytes() == second.read_bytes()


def test_an_empty_timeline_is_refused() -> None:
    """There is nothing to replay, and an empty animation would look like a bug."""

    replay = load_replay_module()

    with pytest.raises(ValueError, match=r"^there\ are\ no\ frames\ to\ replay"):
        replay.build_replay_figure((), title="t")


def test_an_untitled_replay_is_refused() -> None:
    """Every figure in the report says what it is of."""

    replay = load_replay_module()

    with pytest.raises(
        ValueError, match=r"^title\ must\ name\ the\ scenario\ and\ configuration\ shown"
    ):
        replay.build_replay_figure(timeline(), title="")


def test_the_state_timeline_travels_with_the_animation() -> None:
    """Seeing the boxes without the state does not explain a missed brake."""

    replay = load_replay_module()
    frames = (frame(0, state="monitor"), frame(1, state="full_brake"))

    figure = replay.build_replay_figure(frames, title="t")

    assert "full_brake" in figure["frames"][1]["layout"]["title"]["text"]
